Ensure S3 bucket options are properly propagated
lukeshay/astro-aws pull request #125
Opened 2024-03-13 14:08 UTC by SkySails

Thanks for creating this handy project! I found it useful, and would like to help out by fixing a bug I found while using it.

| Q                       | A                                                                             |
| ----------------------- | ---------------------------------------------------------------------------------------------------------- |
| Fixed Issues?           | |
| Patch: Bug Fix?         | Yes |
| Major: Breaking Change? | Possible, explained below |
| Minor: New Feature?     |
| Tests Added + Pass?     |                                                                                                    |
| Documentation PR Link   |                                        |
| Any Dependency Changes? |
| License                 | MIT                                                                                                        |

In the below context:

https://github.com/lukeshay/astro-aws/blob/5a667bef0e852e4c547b8586e04ba8f47bcf363b/packages/constructs/src/constructs/astro-aws-s3-bucket.ts#L43-L48

`this.cdk.s3Bucket` references this getter:

https://github.com/lukeshay/astro-aws/blob/5a667bef0e852e4c547b8586e04ba8f47bcf363b/packages/constructs/src/constructs/astro-aws-s3-bucket.ts#L67-L72

This is most likely a typo, as it causes a circular dependency (`this.#s3Bucket` -> `this.cdk` -> `this.#s3Bucket` etc.).
The result is that it currently isn't possible to set options for the created S3 bucket, such as its name.

This is **possibly** a breaking change because users of this construct _may_ have previously added options to the `cdk.s3Bucket` property. So far, that would have had no effect - but with these changes, they will be applied during the next deployment which might cause unexpected changes.

2024-03-14 02:24 UTC, lukeshay approved these changes
Thanks for the fix!

2024-03-14 02:26 UTC, lukeshay requested changes
I forgot that this needs a changeset associated with it. Could you run `bun run changeset` and follow the prompts?

2024-03-14 02:38 UTC, SkySails commented
I'll do that ASAP! Shall I make it a breaking change or not? There are no API differences, so I would probably make it a patch update, but it's up to you!

2024-03-14 13:12 UTC, lukeshay commented
Just a patch/fix change

2024-03-16 12:44 UTC, SkySails commented
Sorry for the delay! I have added a changeset now.

2024-03-17 15:53 UTC, lukeshay approved these changes

2024-03-17 18:54 UTC, merged